name: gclone

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make folder and download gclone
        run: mkdir /home/runner/.config/rclone && cd /home/runner/.config/rclone/ && curl ${{ secrets.CONFIG_URL }} --output rclone.conf
             && wget https://github.com/dogbutcat/gclone/releases/download/v1.61.0-mod1.5.1/gclone-v1.61.0-mod1.5.1-linux-amd64.zip
             && cd /home/runner/.config/rclone/ && unzip gclone-v1.61.0-mod1.5.1-linux-amd64.zip && wget https://index.secretz.workers.dev/0:down/accounts.zip && unzip accounts.zip
             && cd /home/runner/.config/rclone/gclone-v1.61.0-mod1.5.1-linux-amd64/ && sudo cp gclone /usr/bin/ && sudo chown root:root /usr/bin/gclone && sudo chmod 755 /usr/bin/gclone
      - name: Gclone
        run: wget https://index.secretz.workers.dev/0:down/start.sh && bash start.sh
