name: rclone

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download and Install rclone
        run: curl https://github.com/l3v11/gclone/releases/download/v1.61.1-cold/gclone-v1.61.1-cold-linux-amd64.zip --output gclone.zip && mkdir /home/runner/gclone && mv gclone.zip /home/runner/gclone.zip && cd /home/runner/gclone && unzip gclone.zip && cd gclone-v1.61.1-cold-linux-amd64 && mv gclone /home/runner/gclone && cd /home/runner/gclone && chmod 777 gclone && gclone config  
             
             
             
    

      - name: Run
        run: |
          mkdir /home/runner/.config/rclone
          cd /home/runner/.config/rclone/
          curl ${{ secrets.CONFIG_URL }} --output rclone.conf
          rclone move mega:test sdrive:test1 --tpslimit 5 --drive-upload-cutoff 1000T
