name: rclone

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make folder and download gclone
        run: mkdir /home/runner/.config/rclone && cd /home/runner/.config/rclone/
             && wget https://github.com/l3v11/gclone/releases/download/v1.61.1-cold/gclone-v1.61.1-cold-linux-amd64.zip
      
      - name: Unzip
        run: cd /home/runner/.config/rclone/ && unzip gclone-v1.61.1-cold-linux-amd64.zip
             
             
             
    

      - name: Run
        run: |
          mkdir /home/runner/.config/rclone
          cd /home/runner/.config/rclone/
          curl ${{ secrets.CONFIG_URL }} --output rclone.conf
          rclone move mega:test sdrive:test1 --tpslimit 5 --drive-upload-cutoff 1000T
