name: gclone

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make folder and download gclone
        run: mkdir /home/runner/.config/rclone && cd /home/runner/.config/rclone/ && curl ${{ secrets.CONFIG_URL }} --output rclone.conf
             && wget https://github.com/l3v11/gclone/releases/download/v1.61.1-cold/gclone-v1.61.1-cold-linux-amd64.zip
      
      - name: Unzip
        run: cd /home/runner/.config/rclone/ && unzip gclone-v1.61.1-cold-linux-amd64.zip
             
      - name: cd to gclone and setup gclone
        run: cd /home/runner/.config/rclone/gclone-v1.61.1-cold-linux-amd64/ && sudo cp gclone /usr/bin/ && sudo chown root:root /usr/bin/gclone && sudo chmod 755 /usr/bin/gclone && gclone sync sdrive: sbackup: -P
