name: rclone

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download and Install rclone
        run: sudo curl https://rclone.org/install.sh | sudo bash

      - name: Run
        run: |
          mkdir /home/runner/.config/rclone
          cd /home/runner/.config/rclone/
          curl ${{ secrets.CONFIG_URL }} --output rclone.conf
          rclone copy sdrive:soogsx sdrive:'Secret/Homework/[NSFW-ONLYFANS-LEAKS]/Onlyfans/' --tpslimit 5 --drive-upload-cutoff 1000T
